# permissions for end users to view balancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: balancer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: balancer
    app.kubernetes.io/part-of: balancer
    app.kubernetes.io/managed-by: kustomize
  name: balancer-viewer-role
rules:
- apiGroups:
  - exposer.xincechen.io
  resources:
  - balancers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - exposer.xincechen.io
  resources:
  - balancers/status
  verbs:
  - get
