# permissions for end users to edit balancers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: balancer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: balancer
    app.kubernetes.io/part-of: balancer
    app.kubernetes.io/managed-by: kustomize
  name: balancer-editor-role
rules:
- apiGroups:
  - exposer.xincechen.io
  resources:
  - balancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - exposer.xincechen.io
  resources:
  - balancers/status
  verbs:
  - get
